import { file_exists } from "std/fs"
import { env_var_get } from "std/env"

main(args) {
    let key = env_var_get("AGE_IDENTITY_FILE") failed {
        echo "AGE_IDENTITY_FILE not set"
        fail 1
    }
    if key == "" {
        echo "AGE_IDENTITY_FILE not set"
        fail 1
    }

    if len(args) < 2 {
        echo "Usage: decrypt-secret <file.age>"
        fail 1
    }

    let file = args[1]

    if not file_exists(file) {
        echo "File not found: {file}"
        fail 1
    }

    $ age --decrypt -i "{key}" "{file}" $ failed {
        echo "Failed to decrypt {file}"
        fail 1
    }
}
